#!/bin/bash
set -euo pipefail
set -x

export SKYSCRAPER_HOME="$(cd "$(dirname "$0")/../.." && pwd)"
source "${SKYSCRAPER_HOME}/supplementary/workflows/core.sh"

_test_android() {
   local -r res="$(file "$TARGET_BIN")"
   echo "$res" 
   echo "$res" | grep "$1"
}

_smoke_test() {
    # Qt5
    /usr/local/bin/Skyscraper --buildinfo | grep -q -oPz "(?s)Skyscraper:\s+\d+\..+Qt:\s+5\."
    # Qt6
    "${SKYSCRAPER_HOME}/Skyscraper" --buildinfo | grep -q -oPz "(?s)Skyscraper:\s+\d+\..+Qt:\s+6\."
}

main() {
   case "${1:-}" in
      "android-aarch64") _test_android "aarch64";;
      "android-arm") _test_android "ARM" ;;
      *) _smoke_test ;;
   esac
}

main "$@"
